title: Kamal Carter
email: krcarter@andrew.cmu.edu
linkedin: kamalcarter
description: I just like to build robots.

markdown: kramdown

paginate: 15
paginate_path: "/blog/page:num/"

collections:
  projects:
    output: true
    permalink: /projects/:path/

plugins: [
  jekyll-paginate
]
